export const FETCH_USER_REQUEST = 'profile/FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'profile/FETCH_USER_SUCCESS';
export const FETCH_USER_POSTS_REQUEST = 'profile/FETCH_USER_POSTS_REQUEST';
export const FETCH_USER_POSTS_SUCCESS = 'profile/FETCH_USER_POSTS_SUCCESS';
