version: "3.7"
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - gateway
    volumes:
      - data/

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - ./node_modules:/frontend/node_modules
    ports:
      - 8080:8080
    command: yarn start

  backend:
    depends_on:
      - db
    build:
        context: .
        dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/src:/usr/src/backend/src
    networks:
      - gateway
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - gateway
    command: yarn workspace backend run start

networks:
  gateway:
    driver: bridge

volumes:
  data: