export const FETCH_CONFIG_REQUEST = 'config/FETCH_CONFIG_REQUEST';
export const FETCH_CONFIG_SUCCESS = 'config/FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_FAILURE = 'config/FETCH_CONFIG_FAILURE';
